// Trims and encodes each source clip into a short muted loop under a byte
// budget, writes a poster frame, the typed manifest and the credits file.
// Requires ffmpeg and ffprobe on PATH (ffmpeg 9 verified).
import { execFile } from "node:child_process";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { presets, videos } from "./videos.manifest.mjs";

const run = promisify(execFile);
const srcDir = new URL("../assets/videos-src/", import.meta.url);
const outDir = new URL("../public/videos/", import.meta.url);
const noWebm = process.argv.includes("--no-webm");
await mkdir(outDir, { recursive: true });

async function probeDuration(file) {
  const { stdout } = await run("ffprobe", [
    "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", file,
  ]);
  return Number(stdout.trim()) || 0;
}

async function encodeMp4(input, output, preset, clip, crf) {
  const vf = `scale=${preset.width}:${preset.height}:force_original_aspect_ratio=increase,crop=${preset.width}:${preset.height},fps=${preset.fps}`;
  await run("ffmpeg", [
    "-y", "-loglevel", "error",
    "-ss", String(clip.trim?.start ?? 0),
    "-t", String(Math.min(clip.trim?.duration ?? preset.maxDuration, preset.maxDuration)),
    "-i", input, "-an",
    "-vf", vf,
    "-c:v", "libx264", "-profile:v", "main", "-pix_fmt", "yuv420p", "-preset", "slow", "-crf", String(crf),
    "-movflags", "+faststart", output,
  ]);
}

async function encodeWebm(input, output, preset, clip) {
  const vf = `scale=${preset.width}:${preset.height}:force_original_aspect_ratio=increase,crop=${preset.width}:${preset.height},fps=${preset.fps}`;
  await run("ffmpeg", [
    "-y", "-loglevel", "error",
    "-ss", String(clip.trim?.start ?? 0),
    "-t", String(Math.min(clip.trim?.duration ?? preset.maxDuration, preset.maxDuration)),
    "-i", input, "-an", "-vf", vf,
    "-c:v", "libvpx-vp9", "-b:v", "0", "-crf", "36", "-row-mt", "1", output,
  ]);
}

const entries = [];
const credits = ["# Video credits", "", "Short muted loops. Sources and authors per clip:", ""];

for (const clip of videos) {
  const preset = presets[clip.preset];
  const input = fileURLToPath(new URL(`${clip.key}.mp4`, srcDir));
  try {
    await stat(input);
  } catch {
    console.log(`skip  ${clip.key}: no source in assets/videos-src`);
    continue;
  }
  const mp4Out = fileURLToPath(new URL(`${clip.key}.mp4`, outDir));
  const webmOut = fileURLToPath(new URL(`${clip.key}.webm`, outDir));
  const posterOut = fileURLToPath(new URL(`${clip.key}-poster.webp`, outDir));

  let crf = preset.crf;
  let bytes = Infinity;
  for (let attempt = 0; attempt < 4; attempt += 1) {
    await encodeMp4(input, mp4Out, preset, clip, crf);
    bytes = (await stat(mp4Out)).size;
    if (bytes <= preset.budgetBytes) break;
    crf += 2;
  }
  if (bytes > preset.budgetBytes) {
    console.error(`FAIL  ${clip.key}: ${(bytes / 1e6).toFixed(2)} MB over budget at crf ${crf}`);
    process.exitCode = 1;
  }
  let webm = null;
  if (!noWebm) {
    try {
      await encodeWebm(input, webmOut, preset, clip);
      webm = `/videos/${clip.key}.webm`;
    } catch (err) {
      console.log(`webm  ${clip.key}: skipped (${err.message.split("\n")[0]})`);
    }
  }

  const { stdout: png } = await run(
    "ffmpeg",
    ["-loglevel", "error", "-i", mp4Out, "-frames:v", "1", "-f", "image2pipe", "-vcodec", "png", "-"],
    { encoding: "buffer", maxBuffer: 64 * 1024 * 1024 },
  );
  await sharp(png).webp({ quality: 72 }).toFile(posterOut);
  const blur = await sharp(png).resize(24).webp({ quality: 40 }).toBuffer();
  const duration = await probeDuration(mp4Out);

  entries.push({
    key: clip.key,
    mp4: `/videos/${clip.key}.mp4`,
    webm,
    poster: `/videos/${clip.key}-poster.webp`,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    width: preset.width,
    height: preset.height,
    duration: Math.round(duration * 10) / 10,
    bytes,
    position: clip.position ?? "50% 50%",
  });
  credits.push(`- \`${clip.key}\`: ${clip.author ?? "Al-Hashar"} (${clip.platform ?? "company material"})${clip.page ? `, ${clip.page}` : ""}`);
  console.log(`ok    ${clip.key}: ${(bytes / 1e6).toFixed(2)} MB, crf ${crf}, ${duration.toFixed(1)} s${webm ? ", webm" : ""}`);
}

const lines = [
  "// Generated by scripts/optimize-videos.mjs. Do not edit by hand.",
  "export type VideoAsset = {",
  "  key: string;",
  "  mp4: string;",
  "  webm: string | null;",
  "  poster: string;",
  "  blurDataURL: string;",
  "  width: number;",
  "  height: number;",
  "  duration: number;",
  "  bytes: number;",
  "  position: string;",
  "};",
  "",
  "export const videos: Record<string, VideoAsset> = {",
  ...entries.map((e) => `  ${JSON.stringify(e.key)}: ${JSON.stringify(e)},`),
  "};",
  "",
  "export function getVideo(key: string | null | undefined): VideoAsset | null {",
  "  return key ? (videos[key] ?? null) : null;",
  "}",
  "",
];
await writeFile(new URL("../src/data/videos.generated.ts", import.meta.url), lines.join("\n"));
await writeFile(new URL("CREDITS.md", outDir), credits.join("\n") + "\n");
const existing = await readFile(new URL("../src/data/videos.generated.ts", import.meta.url), "utf8");
console.log(`\nwrote videos.generated.ts with ${entries.length} clip(s), ${existing.length} bytes`);
