import { mkdir, readFile, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";
import { photos } from "./photos.manifest.mjs";

const srcDir = join(process.cwd(), "assets", "photos-src");
const outDir = join(process.cwd(), "public", "images");
await mkdir(outDir, { recursive: true });

const manifest = {};
const credits = [
  "# Photography credits",
  "",
  "All photographs are used under the Unsplash or Pexels free licence.",
  "",
  "| File | Photographer | Source |",
  "|---|---|---|",
];

for (const photo of photos) {
  const src = join(srcDir, `${photo.key}.jpg`);
  if (!(await stat(src).catch(() => null))) {
    console.log(`missing ${photo.key}`);
    continue;
  }
  const image = sharp(await readFile(src), { failOn: "none" }).rotate();
  const meta = await image.metadata();
  const width = Math.min(meta.width ?? photo.maxWidth, photo.maxWidth);
  const out = join(outDir, `${photo.key}.webp`);
  const info = await image
    .clone()
    .resize({ width, withoutEnlargement: true })
    .webp({ quality: 78, effort: 5 })
    .toFile(out);
  const blur = await image
    .clone()
    .resize({ width: 24 })
    .webp({ quality: 40 })
    .toBuffer();
  manifest[photo.key] = {
    src: `/images/${photo.key}.webp`,
    width: info.width,
    height: info.height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  };
  credits.push(
    `| ${photo.key}.webp | ${photo.photographer} | [${photo.platform}](${photo.page}) |`,
  );
  console.log(`${photo.key}: ${info.width}x${info.height} ${Math.round(info.size / 1024)} KB`);
}

const ts = `// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof images;
`;
await writeFile(join(process.cwd(), "src", "data", "images.generated.ts"), ts);
await writeFile(join(outDir, "CREDITS.md"), credits.join("\n") + "\n");
console.log(`wrote ${Object.keys(manifest).length} images`);
