// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const images = {
  "hero-muscat-coast": {
    "src": "/images/hero-muscat-coast.webp",
    "width": 2600,
    "height": 1690,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOgO4AdXgjPywrr9CgA/uevL2fYdz2AnZlEHLsMPmBacGQbaSWpG9W3VCwa4mfKSOn6UEHBZuTaw1pGyUc3Gzpe6jFCZiE+CoMfDbYUfM6WNvP/3gIWxsbewUPlTHx8nXMbKFCooQ5q1wAAAA=="
  },
  "plane-hajar-sunset": {
    "src": "/images/plane-hajar-sunset.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JZgCdL1yB0SywGVbHejsAAP6vBZAqjRkuTL7fYY2l9HHAFwWS+6zG8FR7kk3V2R3ZFtoqPHGlOYJK9ggz0AAA"
  },
  "dest-wahiba-dunes": {
    "src": "/images/dest-wahiba-dunes.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMYJn/AaFt1+GwH3WI1AAD+gy1jgZ5pD2giP5VEplKMVQM1qLqUQl/a0HQaItFWH3r56ermfEv7nDe3yCabww/V0YrtIUdpDWLt91ojurgiVL45KMPvEI5gAAA="
  },
  "dest-muscat-mutrah": {
    "src": "/images/dest-muscat-mutrah.webp",
    "width": 2000,
    "height": 2996,
    "blurDataURL": "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAADQBgCdASoYACQAPu1krVGppSQiqrgKATAdiWIAyMtoenBkiQAI+/br/SoJYe8IfqZ8F/bkVdf61ap63jb5IkAA/t5pgsIVR0Tcux2C72WbW2Oo8CJLLK8tf4So+W3kjhv6i96mSjZX4e4j0rlDNXGSTLxE8KvarMoWTw8rJ4z34SzPl0SDLYpLzE+VTdd2kba5GsLyoubn2i2VZhZLmzV9rsmG7+RwM/2Gs7s4dvRo4LhfS/1Js5OVR8UZHSxRMsSLjlqswXvNwLNsexzgUwetD+wXlZzFs1/GeFmvAg5r5QrMf5OJWJYE/3QigtbEZhGRjWWfiN8sU8AA"
  },
  "dest-muscat-skyline": {
    "src": "/images/dest-muscat-skyline.webp",
    "width": 2000,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwBACdASoYABMAPulep02pJSOiN/VYASAdCWcAw3AQ61+MyOEhUGU/VFcvAP7QAP7x0+DZfwbpui2IDMvvO1jOi8t+ECKDQF3MTnRwcilPiSNin0M2YboNgsKPjqDBylrLN8kEAUUsmpLMMRjNGG5VQ6VBmYiZAAA="
  },
  "dest-jabal-akhdar-terraces": {
    "src": "/images/dest-jabal-akhdar-terraces.webp",
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOmUGUgaS8zgH2AhFA5BNT6TWwscAD+apcfzZEr2tsSpPP70VoAvlyWRZtf2GJmYvdjTtxkUgmXkPc9AV5lZC+hWbmQ1Lo8MDGsLUaW0UqK1GUAV3hWVNBFe11oxese1zsT7rGOHeuw0iJecqPRBWhG5drPgyqUi7tvhUQh8O2dORtArtI3AAA="
  },
  "dest-jabal-akhdar-village": {
    "src": "/images/dest-jabal-akhdar-village.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdMoACYrNMnRCdQosPLw53AAD+0KHXohXkm12R4DyQhsM1DptkDs+R+Dinl4byOldj9L1vgIKhSxyU0Ccxg6kzwtXeavl3fJRg6i+Buv99eTdNvZ/S/ylkdh/TJjQqjR+5enRmGRVJnjSKKAAA"
  },
  "dest-nizwa-fort-sunset": {
    "src": "/images/dest-nizwa-fort-sunset.webp",
    "width": 2000,
    "height": 3000,
    "blurDataURL": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAACwBgCdASoYACQAPu1qp0+ppiMiKqwBMB2JQBUk9WC8A4dFz/Sk6FdQkBz+hIIPI3lpwvDoutHc1LAqv6q/AADiBArS1Fwek9ZraApBnfT7Z8oyPL/uqrzQAmECHpbQ9WjWbTL37G65HOlELLCelgjwxrV56VPsTHpyB2dl5w9QfGST9xYQxFaYQIgZXgptR0bWd2pJ0oa1xR/dviPx7YCP4oddxmUl9ZHdKFuPEQ9M3VaWzAy4zDeJ/+9uLqKfqBDbUheTO7w8gxxRnRcIFAAA"
  },
  "dest-nizwa-fort-palms": {
    "src": "/images/dest-nizwa-fort-palms.webp",
    "width": 2000,
    "height": 2667,
    "blurDataURL": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAABQBgCdASoYACAAPu1opU2ppiMiMBgMATAdiWwAnTKAhlQxYT8f+edLjmXoMARuSBHLKTEevti56v0lAAD+zyJl5E5wNF/V1WyMVN/5GnOYfpmBn2Mh2bY4J/oX9q6pPy88KRHMla0QbY1qA1nkIah+o9nrcrik2ocQXji4T8nwJBIbOZhRNwbwI+C2jhaGYhDEJpSziwHQfE3oht7LwN6nQeoYtZ69kIHgrMVK7QeM9M7vinKzQAfazCDR5fh4/HbI9e1YZ3bRrr2gadEfsat5tnqp1RfYX+XN+tQOR9yQpy88IMeg3gLrLeKNqyxiny8SxsR+BglftL6L6GJl9ifw3ocHV5kG/5y99CEQxc7dB1MNYTAtLmBLAAA="
  },
  "dest-wadi-shab-pool": {
    "src": "/images/dest-wadi-shab-pool.webp",
    "width": 2000,
    "height": 2667,
    "blurDataURL": "data:image/webp;base64,UklGRjABAABXRUJQVlA4ICQBAABQBgCdASoYACAAPu1gp02ppSOiMAgBMB2JYgCo+3gd4NUG0BVMa0Z/oknULaw8g7XVJc/aUaKEH7AgAADK8qVuNMzpkfDJGbynGisvCZCEdb8kFp9Jk9fBmTHJu3V48yZUvo/SuoTSxN4qekuha62V+lR1rd95Pp/Jd574WOgqOXGXy2EEG2pavhlIqKteCDsgfDqwocti0zAyomYAqwtGzrVVeVfhLlr1qfxXrhTRc22GVakS7g/SLnPSp34/clMNlHdLIJLKizZsAz40p4jBq4NbCeXFEsGacNYQCdSV6SR5MSi6WU2QjyoDxXXSqYgZ5iNHW/SQA3HsZUHlteT0R4pYYv26/PI68Zg9jDXc3Gent24WpQ6elPCeK1+6sd0bggAA"
  },
  "dest-wadi-shab-canyon": {
    "src": "/images/dest-wadi-shab-canyon.webp",
    "width": 2000,
    "height": 2500,
    "blurDataURL": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAAAQBgCdASoYAB4APu1kpk4ppaMiMBgMATAdiWIAnTNnPKhzBxiqKSg6qsLUyzCA3m6A6orDuCitYUAA/uYGsi4B4G3CdTylT+NmEIIMBeiuwnVqBQQvBJfotc4ImFVkjadFoGL+URkUv9TzQCczi7v4wkYpUh/fsqV/qYMLVHgAx+KG08bWmD+I3d52ygrpctcIZR6YA+Y2GCJXYvotZY9IPTV1TACbK0bQ4U/AdTXVv5oqmeVizI8zFxLHxZFSrupaZkfWMZOdt9BF3IBhCIAAcpSXgo/q4AA="
  },
  "dest-musandam-fjords": {
    "src": "/images/dest-musandam-fjords.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwAwCdASoYABAALrV2u12jqampiYC0SygFYAIdXEm1vWENRAAA/ucog4QWw5NtYRtJPRTilnkk8yEM/oG7N83iwsJzmG6WeiJ+fqnW+G0JhGi50YmuAAAA"
  },
  "dest-musandam-dhow": {
    "src": "/images/dest-musandam-dhow.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOgBH21CzTceRIhCdyAAP6C8LqFVD05qGVFHxUdjBxjRqi/FYhHFhdUU51W0Og13+Zq1J3MFcRwEAA="
  },
  "extra-musandam-cliffs": {
    "src": "/images/extra-musandam-cliffs.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOgApcn6vdkDVMIGIAA/qapcG9vezdwiULjiw+zqNIIPQk2443s9DwcFBnSkpggLgCGdez+ymIcXSwbubnv7VYG+RtT6/zA1te2Uu0X0sc7pwZt7otyjcgh9CE3hjiCqJNAocVHmE5ymvZuq4Y07jyAAA=="
  },
  "extra-grand-mosque-corridor": {
    "src": "/images/extra-grand-mosque-corridor.webp",
    "width": 2000,
    "height": 3000,
    "blurDataURL": "data:image/webp;base64,UklGRgwBAABXRUJQVlA4IAABAADwBgCdASoYACQAPu1kqk8ppSOiMBVaqTAdiWIAwPzuw62sBjDnuYFswx/G1hxO5w7T5R7Wf/9zmPdXxTX5m9EAAPhMwsm9g81ONO/wBMwSGuthv1fPPvrgcOpIBtgD+/3Xz/KvxzOzX0neVO59OHFGCXbr62IGW1D0Qt+8STxxW/1B5q04BnWgFRq4Pd//VivgVvUEcbD/pmBFPpCbmwgqiuIxwAtRr+00Mwv0S7LHY8/X4m22/3NYhnLNBkD/s1YLsczxYXcO+2GpgDK+LL+XWUgfaaC/PJR1li43geDgyrWdLzvvsJ8xelDBksQTqKD1E6XfGF1v2OaYkWsggAAA"
  },
  "umrah-haram-night": {
    "src": "/images/umrah-haram-night.webp",
    "width": 2600,
    "height": 1463,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYwCsACP7foYt0NCyijhgAAD+J2KTae7fXfcRnViVKTbWtgY59mqFWKeqHaOOTbfyJC2a2JdhtKALBXmN8gSIcPQvSqlBLll1m4OXSq2Nm7wkhx7OtmkuFyDOiBPpdRPdcyHNNRunX98AAAA="
  },
  "plane-dunes-daylight": {
    "src": "/images/plane-dunes-daylight.webp",
    "width": 2600,
    "height": 1463,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JagCdEf/gPInCnTJFkwAA/tT/Gygt4VtzrkxkahfuFlvSoEuwawwH5IpFr+TxNpnd3q3WY9gPOJD9WBctJIaBOkDnnDxwhdc6Q9gA"
  },
  "jebel-shams-rim": {
    "src": "/images/jebel-shams-rim.webp",
    "width": 2400,
    "height": 1351,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBACdASoYAA0APu1iqk2ppaQiMAgBMB2JZACdMoR3ACmPLseVAMZgTuwa594AAOIExkN8reDJ1wR2Lmuj8guqC3DUbUbeMrtUUGqIFjUJeSkX6aj9AUGE7kxTl1/PAcGXluiJtdyvfFw8yDuhncLepFE88kuo5rGM1+3EOIML+CgAAAA="
  },
  "nakhal-fort": {
    "src": "/images/nakhal-fort.webp",
    "width": 2400,
    "height": 1601,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYABAAPu1qrU8ppiQiMAgBMB2JaACdOUE6UAxkstPLDV317vSzrAD98GIiUa2kVNNlRQ9JYQbvJ2MsYw6DK/t3tZnr1FjwhsByTjEYd2fSAh0CgxaITO+G5J/zXJbkH9FyoMQzVgQ0ysiDoP1KHd6a+HWbv5NcMSPGTgMNu48AAA=="
  },
  "dolphins-muscat": {
    "src": "/images/dolphins-muscat.webp",
    "width": 2400,
    "height": 1598,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JZQC7AB9eeczJhqNIe7WAANvtExiEn1Fd/UmYRIJB0AfhNOLawG86Syottz8VQdZmhem2IBx8vYxsw+Y3V+xrmJFAbPlmT2KAKwqFHRI42MLNHYhIISJss5FgAA=="
  },
  "dhow-turquoise": {
    "src": "/images/dhow-turquoise.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBQCdASoYABIAPu1sq1EppaOiqAqpMB2JZACdMuN1XvgALNyXgf6wpLN4BQRX1bDB7t4AAP7ftbbd9M2lefdmaQFAEIFq3ByzCryeojrIaQPHwcmkI7SbEmnwLBvLO8QkFUYYYNDXlqhoS00Tiz7SHKqx4JURYtyrRR5c/vyKXkppUFpfM52Gfy6GsD418ubIjj4LAAA="
  },
  "bimmah-sinkhole": {
    "src": "/images/bimmah-sinkhole.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZQDG9CG5aGjDm5eFKnAAyQF3AEy4ERik08s/c0tET8GiJXNkrlJlwwDG70IzWtV5151dYHcYXPa1PkyRJmBJqw16NH5kqO+jnvPGGB0zVPJLX70Xki0RiNHhRvSNHS+zyI1oY4RwjjIaZ6V3O8BURQZXcQRjcvM31BIeijgAAA=="
  },
  "grand-mosque-chandelier": {
    "src": "/images/grand-mosque-chandelier.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoMxmo3AXxLgBn35rstsXDPbeAAA/qaeLPOEwFvBaY0t+PneSnAKmBKKf4ejb39gWnkJ8geFHVPhzlmKfquvky9YTgiiCXJX1a4F1MFXcFdYjmYSO8ythkTRaR3guME1nHhDm+1Qw5Qr43t5p5rPs9/4rB+z/iwkY89k/m/3BYvt0OIAAAA="
  },
  "sur-lighthouse": {
    "src": "/images/sur-lighthouse.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAwCdASoYABAAPu1kqU2ppaQiMAgBMB2JQBOgBDv1d+cepLrYAP5QUN6UoNS3uIw50qYL4wCZDEOfIKSAIGG0BsL6WQTQHNCol4AL0E+2DJ+zIv+9gDfnjgQBpsuCtpoAAA=="
  },
  "world-dubai": {
    "src": "/images/world-dubai.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwBACdASoYABIAPu1crE2ppKSiMBgMATAdiWMAsOwQ61+jMs6fHXDi2zFPgAD+rwYkRjc2LqQx34gGn2gUQBsgZfkri65XcikXu5/oFJegh6F/UBEc3nx4U39ojghwYtJZBp+YX/DnFsjT8jZoAA=="
  },
  "world-istanbul": {
    "src": "/images/world-istanbul.webp",
    "width": 2400,
    "height": 3600,
    "blurDataURL": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBgCdASoYACQAPu1orVCppaQipWzJMB2JYwDE2DnhsFbC0HphUl0NqwHEC0OR1ge8ALYWW7NQnGAA/sOaIVLUAu7H37eh5/SrJ4MthivlX+rtAgVxhJUiFKBkmnkG6c4tF9UzPsL3ZoqmLxzn13NGbag6XQi6yIbvDgyiKUjcu8rq7gXlJIYfvo1jqHM4Em9DV87B1D8qpEt5XcltgH52752i9uuahMvKNda1OkN+SxcQEZ5pw9lwLuMHdAgA"
  },
  "world-thailand": {
    "src": "/images/world-thailand.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwBQCdASoYABIAPu1gq1AppKOisBgIATAdiWgAnTKEdWgYvVgGBkrsLx51ZfnJRDVCvJo68bwhAADxkhVDJft+LdQx7ojD+3c9oI1V28MjWcLt8k9nlAro/BMkBuvh+wuVl9D7IC6e45LdroQ42kOc0eqAsXjehAGF23mBBbwlswo/hZi8nVrS+yAk8vPZbsEWtQFqTdp0WyxTIxGrIov3qQAAAA=="
  },
  "world-malaysia": {
    "src": "/images/world-malaysia.webp",
    "width": 2400,
    "height": 3600,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBQCdASoYACQAPu1qrVEppaQipWzJMB2JQAXf+Bgs14gYu4pHVykVNMhzjilg+1UBEPAA/ueTTVR5dV6MGw+J/zCTf7o7d2uPZhKyut2nc0heBuCkXt7vjaVaome5yWqNN5VQR3IbrIGCZoio/sbHH2uWXg6odyTTSy/f4VIPMHa7GD3FxdkTc7rOuyOwNnONoGmJC7mX87inSZWKO58DhPwAAA=="
  },
  "world-georgia": {
    "src": "/images/world-georgia.webp",
    "width": 2400,
    "height": 3200,
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADwBACdASoYACAAPu1qqlEppaOiqAqpMB2JagCdAGii2IDyoNyNUn3rG4DRmWlVGyAA/IDSfhJEswiS5/9dHIvgnxvuN3sfrLj8mnu2nfcNfVIt9uUGgjTBiATnRDdYxPHaUdTRtMWozoVm7dpnuHflbhrrhD1h1oDoFMWkOToW5EBK9t0waPIHFIG/GvcdK8EYBmR6koE3HhMWPHBfLck1V5oz/t5iAHqYAA=="
  },
  "world-azerbaijan": {
    "src": "/images/world-azerbaijan.webp",
    "width": 2400,
    "height": 3600,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwBQCdASoYACQAPulgpk2pJaOpNVgIASAdCWMAyFxFbR3BoCzyHYBUH0pFmPFF2J99iIVtFO5wyAD+uPWBmURGDnUEcc5njdCkwkicqUYk8RpYNqPGfxCoighU1iIvG1LPtCHLeOkiypdYp/JEnCJdXiFNR72iyA0PJC9Bv6BvlgL8Gqq3BxYokhgFXJ4YascMI8JkYyuXveoTugAAAA=="
  },
  "world-switzerland": {
    "src": "/images/world-switzerland.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoYAA0APu1kqk4ppaQiMAgBMB2JZQCdACHiHcPxtKXmNNtgAP6QZi7VlOkTx8/fgQ2DmYkE7HWqBbviQiy6ns4lUF9PUr9Ha2mjnjqAAAA="
  },
  "world-bosnia": {
    "src": "/images/world-bosnia.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdEf/gN4y8yXGmgCoaBAAA/j2l/bgBeIL66VCBxx1DPq6Ha28IaMSn2ePUAfK0WV0HR2utx3bpVzv9z9a0erYtgANHNK9BssoJ601sfvmcQem99P8G/8xlT3Q/n3fu+Qfxow5esx47emXX3wNfpEtPu87E8k9hoUjFs01hd5qoLmerPtFx+f2HiFLJ7cvSoU8bZk5m1XZRYAA="
  },
  "world-india": {
    "src": "/images/world-india.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoR3ACrO4fpHYONbOCmlYAD8dwh6nlRHzNJZkhGZ04MdKFUkOvbN0kmmh4CLAYEWsZrVinrel655phAG5i5e+OwEE9xVzdKq4hnd84nRLCNrntMsnzB/mX6jb+CpVE0qMhlsxMNgPq1PwCbhlFPYOlf4NKRhxQYbIMysT8maCygAAA=="
  },
  "world-greece": {
    "src": "/images/world-greece.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoYABAAPu1kq04ppaQiMAgBMB2JQBOkGQBOXcX9FFu1NZKtCAAA/tp1oICxktHCs44mtpXgtKWMdKaB4f7WHtAOZ789Ynt2vLVEezfCMypZOQSEHjJlKQgTzOFDkNASLeNjWp3yAAA="
  },
  "world-kenya": {
    "src": "/images/world-kenya.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoRwFf/gMOn9pLouf/nGAAD5tjnv4WwnHDiXifwImjG2DIVyF66rMtkMv+VV31nAwj8L9HmjFx4XT6FEScA/qutXu3ZC8wGa+idygHxT8Rw4kDsJ2cf+9a0jE5LbRlBQ1U1+673IqG3HoAAA"
  },
  "world-france": {
    "src": "/images/world-france.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdABjSxXU1NHfKolGdgAD9HgonPb+te6Krhr48eqKnH/Hrali867YE0ShfBRFNINByprbF2qp7XCliP2gs3lhr1VbDc8bt6tkQr4AAAA=="
  },
  "world-sri-lanka": {
    "src": "/images/world-sri-lanka.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoYABIAPu1mqU2ppaQiMAgBMB2JYwDA3A6er/ScSpsC08YN7RDjAAD+E4AEQ/Becw3+AWsr+qm6H/Zq7rlEgZpjCzqUZDdQmTWZVNUz1V1Goacmr30i4o3Yh19QG1Uxm7+sD0YMhl8WKAkCQAA="
  },
  "world-trabzon": {
    "src": "/images/world-trabzon.webp",
    "width": 2400,
    "height": 2008,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBQCdASoYABQAPu1kq06ppaOiKA1RMB2JZwDG9A3T5CU9V1ttC34jdc8ZKUA2oMR7kAD+zEDyDX95V/MBgIk1UldXmpBn3cy6LVcTYK5AL+fpIE7ogcAIm/MSvz7uHi6GG1PwlAkXlnx21GKHWIYvEtAAAA=="
  },
  "world-kerala": {
    "src": "/images/world-kerala.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoYABAAPu1orU6ppiSiMAgBMB2JZgCdAGjNjUx4hyiDacoA/vqP/JWn+reN5h+TPlfcEZ7lEL+VI+evZwrfhLwsYvvuhk0wT10PG+OX0WN5NZ6uE3ANP19OcuEMLwgAAAA="
  },
  "world-czech-austria": {
    "src": "/images/world-czech-austria.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwBACdASoYABAAPu1iqk2ppaQiMAgBMB2JQBOmUGPhz/gPI/l4nyztz8FjgAD+WNubjkCIh1kFAPedgY0yXXho7AsZW4MO1Mv0SyrAEu6X2AaTpW0uIoc0RBFxRLaoFMRiMsuAAAA="
  },
  "world-scandinavia": {
    "src": "/images/world-scandinavia.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoYABAAPu1mqk2ppaQiMAgBMB2JQBadBFitJmGB1WjkQsgA+yLwRtPRPmd6L+MqhABhnBN6g9KxMhSyPTwhqWUr5Yz/KZNAIaxJqTZcg2tf9jIznMFETdDXmLMGqmk8e/sQAdN8rEmjYAAA"
  },
  "world-qatar": {
    "src": "/images/world-qatar.webp",
    "width": 2400,
    "height": 1356,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBACdASoYAA4APu1iqU2ppaQiMAgBMB2JZgCdMoADUw8DHTKlvXrP43FAAP3h2TDYP6PlF3UIOBpX3qQm/zEntktmUSLIM58ugYr21vjAfY8H5kDAZ5zOU1ctC3dztITfvcWecxg00dLG/GMTAAAA"
  },
  "world-armenia": {
    "src": "/images/world-armenia.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOgAzjE7+p7ngfwAMrzYgLbSN4gaNhYlyPx2wPQFNk1d7lmmphvIGlscwx4EnacOt1z712ZoPzr+M8r2LpTn71gAA=="
  },
  "people-desert-family": {
    "src": "/images/people-desert-family.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBQCdASoYABIAPu1ip04ppaMiMBgMATAdiWQAsR8y7KnAAGBVmF3S1myuRsJpzuaYhJsgAP7ec3RJK5woUWttYJ6+MJddb2XR+Y4S3bsynZuYUfKToj9st6ggUzOsadbm0FE5+IR4ZWzu2eAXyxVGWq1DxR2vr2ZNTR977xXouKFR44IsQgZLRdhje0AuAqNrPS3GxyVyfPVcsZoAAA=="
  },
  "people-dhow-friends": {
    "src": "/images/people-dhow-friends.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZwDE2B4lYS9HF1R4bQCAAP7ghbYp156NyJ/n93LerLrEyj6g1+Ay5npgz/PbKiKOtfmJbrjAPVPzIvK9bz3PUVXB1g6dBSnJsHw07alNJeT8d2WbvIYxiP0AuyEyFZXuU/V36//BqznUAAA="
  },
  "people-mountain-couple": {
    "src": "/images/people-mountain-couple.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQC/OBkwWWPYpRxjB/UeQAD8soFER3EMCby1BvHasWjwjn+lBoxuTW4RHuE711bmLMv8TDDG9fXZcTYhDo5DDoxXtnADXbgCDPb9GP3gH0IytCgYcBRwbbH9rZqJmwEIUb5KYtLA3w1paeyPPBFUAAA="
  },
  "people-wadi-kids": {
    "src": "/images/people-wadi-kids.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdIDZCdw5g1Kil0AjdEFXLegD+jxkF2v81lX4npNRJ3pSvFnHe8FvSzJC0ZAYvX/dhD47TI/TszM//Wa8sdiltieQprdF58Jv3yrc9JOBBnOovG3vgkmyd5pIkR0dZd5AhW0jlEY7n9VyGWl0NxrrcoAAA"
  },
  "people-fort-family": {
    "src": "/images/people-fort-family.webp",
    "width": 2400,
    "height": 3601,
    "blurDataURL": "data:image/webp;base64,UklGRiABAABXRUJQVlA4IBQBAABwBgCdASoYACQAPu1wrlCppqQiqrgKATAdiWIAnTNyQ20gPz8VfXcShbolpLbWqE77QZug7immO1sO8gAA/unKAeujnv9cP6hZkqs15hJOAq74kic/ZizSZUWjSSm06hDvdgAnr1ndcPaIW1xvMsJQGQXAmzkpX7N1y5uKSphcDvVz/Ze1dr81WgIXyIzWA7FfFfhgKYUlr1JDrQJBPijWXo6kDAjfmOI6CWg8mKFQUQPTeDAhCa1sxmPphunMqEo525A9eiAKyl9ZHbzt2tIFeKwZECeG8wLJEVTZxeRV4BDFP0y9I9L+ZFFdhuS/Z5SdHBZ3Z38alVrdAzsEP9HD4T1v+Gfo8LM+89q0BldgAeK+4AA="
  },
  "people-mosque-visit": {
    "src": "/images/people-mosque-visit.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBUegQix9U1EEADN+EWTg0qyGSvhqop0oVXbPhUntVHQjmq0FO8bQFzTqyKSgT73KCV9zkcQIsRMwKr6EpWNWDsdEklNVc2I7XkqhVBfrr0fELlGkZOWu/URzc/zTWdpujWPIj1XByl6gAA="
  },
  "people-airport-family": {
    "src": "/images/people-airport-family.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAwBQCdASoYABIAPu1sqlEppaOiqAqpMB2JYwCuHA3L0GWbir5GizefKnRUJ9bP4OFsgADOOiEXfetkPFaUjMWc4D2BG5SNvrTCF9ZRj/8kGHo1HAQyXscUYWaGzmRcamS0+3Xjj7KPKnDJblC1LYWLsM6E/9G9DzHa9iVqvUtTKWswmWTjfnXTUZC/pR19aqUxST7x5JvscEzlExj8sVMGFuLsa+n4zAA="
  },
  "people-hotel-arrival": {
    "src": "/images/people-hotel-arrival.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoLUDquh6GT/Nmu8M1YqVBFeEMAA/pcc0CJ+A2WYEbeNeT8PnvTOpL0kStpUwL7M6YRjsaP5twRXvepQeQM5C0wy9x8XF4ily/8MCfG9PqyaM3f/UdnOBzxlZQO42z0ap4UfruCLA9ntIHTbLX9rb8PiBvCNCCZVERoehJq3aiaFH3VwN20RbQgcZlNmMMie1pjfrEYAuDkca5/N8vYEnX+xYRDz3ox+yk7rD6AU6VwAAA=="
  },
  "people-holiday-abroad": {
    "src": "/images/people-holiday-abroad.webp",
    "width": 2400,
    "height": 1602,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JYwC+SBrMrLtDQCjsAP7x4FbFV/7l/Q83AsJpAPeS8eNCuFrtyb0VSslRzyU3+khu5T+eVNXx4jaufOsopIrrcL9+gcEE9jTZpeqlCFYBNkIkU6oWAAAA"
  },
  "people-umrah": {
    "src": "/images/people-umrah.webp",
    "width": 2400,
    "height": 3515,
    "blurDataURL": "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAABwBgCdASoYACMAPu1kqlCppSOiqrgMATAdiWMAxn3dI4gQ38UE+NtuZpowOhV7rHoa8PW/KNMiKIBaMyAA8IwC/8KnEoSk6oleRIBO3mbGEErYuledFuNkWA2abQSDvE3lE1hJGzy0Yu0uC/Ep7U19xWVWPfdJk6Ww1UMbOjG59dVDaWBkJVjAbqmTad8iYMmMBiZwaFogBfksDtp+mGyxxuZ0lR/HcPKAnn86C4lrpONDgLjDNAJepFaSBWbv+J0SLgFEk08ogBPmDQss7b8xMafx+CXr2EVo8xF6P6r1Wz/uoIIS9bSFVnpVSyxE7Zo0LBLcKyIGJPNUAAA="
  },
  "extra-al-alam-palace": {
    "src": "/images/extra-al-alam-palace.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JbACdMoRwIsAAszakbjLuVYRw+gAAyoxzgnPoaQW093i82QL5+68b2YwAQGKCWv1bWhvOsapY0Ng1/g2/AgUVVuk6draevAZTKSWI55mm0KsAdtzxrhMoTaMdqYxi9zzn2lzXjBATXLVSEF71fIry6zqHIgfH4d0AAA=="
  }
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof images;
