// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const images = {
  "hero-muscat-coast": {
    "src": "/images/hero-muscat-coast.webp",
    "width": 2600,
    "height": 1690,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOgO4AdXgjPywrr9CgA/uevL2fYdz2AnZlEHLsMPmBacGQbaSWpG9W3VCwa4mfKSOn6UEHBZuTaw1pGyUc3Gzpe6jFCZiE+CoMfDbYUfM6WNvP/3gIWxsbewUPlTHx8nXMbKFCooQ5q1wAAAA=="
  },
  "plane-hajar-sunset": {
    "src": "/images/plane-hajar-sunset.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JZgCdL1yB0SywGVbHejsAAP6vBZAqjRkuTL7fYY2l9HHAFwWS+6zG8FR7kk3V2R3ZFtoqPHGlOYJK9ggz0AAA"
  },
  "dest-wahiba-dunes": {
    "src": "/images/dest-wahiba-dunes.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoMYJn/AaFt1+GwH3WI1AAD+gy1jgZ5pD2giP5VEplKMVQM1qLqUQl/a0HQaItFWH3r56ermfEv7nDe3yCabww/V0YrtIUdpDWLt91ojurgiVL45KMPvEI5gAAA="
  },
  "dest-muscat-mutrah": {
    "src": "/images/dest-muscat-mutrah.webp",
    "width": 2000,
    "height": 2996,
    "blurDataURL": "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAADQBgCdASoYACQAPu1krVGppSQiqrgKATAdiWIAyMtoenBkiQAI+/br/SoJYe8IfqZ8F/bkVdf61ap63jb5IkAA/t5pgsIVR0Tcux2C72WbW2Oo8CJLLK8tf4So+W3kjhv6i96mSjZX4e4j0rlDNXGSTLxE8KvarMoWTw8rJ4z34SzPl0SDLYpLzE+VTdd2kba5GsLyoubn2i2VZhZLmzV9rsmG7+RwM/2Gs7s4dvRo4LhfS/1Js5OVR8UZHSxRMsSLjlqswXvNwLNsexzgUwetD+wXlZzFs1/GeFmvAg5r5QrMf5OJWJYE/3QigtbEZhGRjWWfiN8sU8AA"
  },
  "dest-muscat-skyline": {
    "src": "/images/dest-muscat-skyline.webp",
    "width": 2000,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwBACdASoYABMAPulep02pJSOiN/VYASAdCWcAw3AQ61+MyOEhUGU/VFcvAP7QAP7x0+DZfwbpui2IDMvvO1jOi8t+ECKDQF3MTnRwcilPiSNin0M2YboNgsKPjqDBylrLN8kEAUUsmpLMMRjNGG5VQ6VBmYiZAAA="
  },
  "dest-jabal-akhdar-terraces": {
    "src": "/images/dest-jabal-akhdar-terraces.webp",
    "width": 2000,
    "height": 1333,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOmUGUgaS8zgH2AhFA5BNT6TWwscAD+apcfzZEr2tsSpPP70VoAvlyWRZtf2GJmYvdjTtxkUgmXkPc9AV5lZC+hWbmQ1Lo8MDGsLUaW0UqK1GUAV3hWVNBFe11oxese1zsT7rGOHeuw0iJecqPRBWhG5drPgyqUi7tvhUQh8O2dORtArtI3AAA="
  },
  "dest-jabal-akhdar-village": {
    "src": "/images/dest-jabal-akhdar-village.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdMoACYrNMnRCdQosPLw53AAD+0KHXohXkm12R4DyQhsM1DptkDs+R+Dinl4byOldj9L1vgIKhSxyU0Ccxg6kzwtXeavl3fJRg6i+Buv99eTdNvZ/S/ylkdh/TJjQqjR+5enRmGRVJnjSKKAAA"
  },
  "dest-nizwa-fort-sunset": {
    "src": "/images/dest-nizwa-fort-sunset.webp",
    "width": 2000,
    "height": 3000,
    "blurDataURL": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAACwBgCdASoYACQAPu1qp0+ppiMiKqwBMB2JQBUk9WC8A4dFz/Sk6FdQkBz+hIIPI3lpwvDoutHc1LAqv6q/AADiBArS1Fwek9ZraApBnfT7Z8oyPL/uqrzQAmECHpbQ9WjWbTL37G65HOlELLCelgjwxrV56VPsTHpyB2dl5w9QfGST9xYQxFaYQIgZXgptR0bWd2pJ0oa1xR/dviPx7YCP4oddxmUl9ZHdKFuPEQ9M3VaWzAy4zDeJ/+9uLqKfqBDbUheTO7w8gxxRnRcIFAAA"
  },
  "dest-nizwa-fort-palms": {
    "src": "/images/dest-nizwa-fort-palms.webp",
    "width": 2000,
    "height": 2667,
    "blurDataURL": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAABQBgCdASoYACAAPu1opU2ppiMiMBgMATAdiWwAnTKAhlQxYT8f+edLjmXoMARuSBHLKTEevti56v0lAAD+zyJl5E5wNF/V1WyMVN/5GnOYfpmBn2Mh2bY4J/oX9q6pPy88KRHMla0QbY1qA1nkIah+o9nrcrik2ocQXji4T8nwJBIbOZhRNwbwI+C2jhaGYhDEJpSziwHQfE3oht7LwN6nQeoYtZ69kIHgrMVK7QeM9M7vinKzQAfazCDR5fh4/HbI9e1YZ3bRrr2gadEfsat5tnqp1RfYX+XN+tQOR9yQpy88IMeg3gLrLeKNqyxiny8SxsR+BglftL6L6GJl9ifw3ocHV5kG/5y99CEQxc7dB1MNYTAtLmBLAAA="
  },
  "dest-wadi-shab-pool": {
    "src": "/images/dest-wadi-shab-pool.webp",
    "width": 2000,
    "height": 2667,
    "blurDataURL": "data:image/webp;base64,UklGRjABAABXRUJQVlA4ICQBAABQBgCdASoYACAAPu1gp02ppSOiMAgBMB2JYgCo+3gd4NUG0BVMa0Z/oknULaw8g7XVJc/aUaKEH7AgAADK8qVuNMzpkfDJGbynGisvCZCEdb8kFp9Jk9fBmTHJu3V48yZUvo/SuoTSxN4qekuha62V+lR1rd95Pp/Jd574WOgqOXGXy2EEG2pavhlIqKteCDsgfDqwocti0zAyomYAqwtGzrVVeVfhLlr1qfxXrhTRc22GVakS7g/SLnPSp34/clMNlHdLIJLKizZsAz40p4jBq4NbCeXFEsGacNYQCdSV6SR5MSi6WU2QjyoDxXXSqYgZ5iNHW/SQA3HsZUHlteT0R4pYYv26/PI68Zg9jDXc3Gent24WpQ6elPCeK1+6sd0bggAA"
  },
  "dest-wadi-shab-canyon": {
    "src": "/images/dest-wadi-shab-canyon.webp",
    "width": 2000,
    "height": 2500,
    "blurDataURL": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAAAQBgCdASoYAB4APu1kpk4ppaMiMBgMATAdiWIAnTNnPKhzBxiqKSg6qsLUyzCA3m6A6orDuCitYUAA/uYGsi4B4G3CdTylT+NmEIIMBeiuwnVqBQQvBJfotc4ImFVkjadFoGL+URkUv9TzQCczi7v4wkYpUh/fsqV/qYMLVHgAx+KG08bWmD+I3d52ygrpctcIZR6YA+Y2GCJXYvotZY9IPTV1TACbK0bQ4U/AdTXVv5oqmeVizI8zFxLHxZFSrupaZkfWMZOdt9BF3IBhCIAAcpSXgo/q4AA="
  },
  "dest-musandam-fjords": {
    "src": "/images/dest-musandam-fjords.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwAwCdASoYABAALrV2u12jqampiYC0SygFYAIdXEm1vWENRAAA/ucog4QWw5NtYRtJPRTilnkk8yEM/oG7N83iwsJzmG6WeiJ+fqnW+G0JhGi50YmuAAAA"
  },
  "dest-musandam-dhow": {
    "src": "/images/dest-musandam-dhow.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOgBH21CzTceRIhCdyAAP6C8LqFVD05qGVFHxUdjBxjRqi/FYhHFhdUU51W0Og13+Zq1J3MFcRwEAA="
  },
  "extra-musandam-cliffs": {
    "src": "/images/extra-musandam-cliffs.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOgApcn6vdkDVMIGIAA/qapcG9vezdwiULjiw+zqNIIPQk2443s9DwcFBnSkpggLgCGdez+ymIcXSwbubnv7VYG+RtT6/zA1te2Uu0X0sc7pwZt7otyjcgh9CE3hjiCqJNAocVHmE5ymvZuq4Y07jyAAA=="
  },
  "extra-grand-mosque-corridor": {
    "src": "/images/extra-grand-mosque-corridor.webp",
    "width": 2000,
    "height": 3000,
    "blurDataURL": "data:image/webp;base64,UklGRgwBAABXRUJQVlA4IAABAADwBgCdASoYACQAPu1kqk8ppSOiMBVaqTAdiWIAwPzuw62sBjDnuYFswx/G1hxO5w7T5R7Wf/9zmPdXxTX5m9EAAPhMwsm9g81ONO/wBMwSGuthv1fPPvrgcOpIBtgD+/3Xz/KvxzOzX0neVO59OHFGCXbr62IGW1D0Qt+8STxxW/1B5q04BnWgFRq4Pd//VivgVvUEcbD/pmBFPpCbmwgqiuIxwAtRr+00Mwv0S7LHY8/X4m22/3NYhnLNBkD/s1YLsczxYXcO+2GpgDK+LL+XWUgfaaC/PJR1li43geDgyrWdLzvvsJ8xelDBksQTqKD1E6XfGF1v2OaYkWsggAAA"
  },
  "umrah-haram-night": {
    "src": "/images/umrah-haram-night.webp",
    "width": 2600,
    "height": 1463,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JYwCsACP7foYt0NCyijhgAAD+J2KTae7fXfcRnViVKTbWtgY59mqFWKeqHaOOTbfyJC2a2JdhtKALBXmN8gSIcPQvSqlBLll1m4OXSq2Nm7wkhx7OtmkuFyDOiBPpdRPdcyHNNRunX98AAAA="
  },
  "plane-dunes-daylight": {
    "src": "/images/plane-dunes-daylight.webp",
    "width": 2600,
    "height": 1463,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JagCdEf/gPInCnTJFkwAA/tT/Gygt4VtzrkxkahfuFlvSoEuwawwH5IpFr+TxNpnd3q3WY9gPOJD9WBctJIaBOkDnnDxwhdc6Q9gA"
  },
  "jebel-shams-rim": {
    "src": "/images/jebel-shams-rim.webp",
    "width": 2400,
    "height": 1351,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBACdASoYAA0APu1iqk2ppaQiMAgBMB2JZACdMoR3ACmPLseVAMZgTuwa594AAOIExkN8reDJ1wR2Lmuj8guqC3DUbUbeMrtUUGqIFjUJeSkX6aj9AUGE7kxTl1/PAcGXluiJtdyvfFw8yDuhncLepFE88kuo5rGM1+3EOIML+CgAAAA="
  },
  "nakhal-fort": {
    "src": "/images/nakhal-fort.webp",
    "width": 2400,
    "height": 1601,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYABAAPu1qrU8ppiQiMAgBMB2JaACdOUE6UAxkstPLDV317vSzrAD98GIiUa2kVNNlRQ9JYQbvJ2MsYw6DK/t3tZnr1FjwhsByTjEYd2fSAh0CgxaITO+G5J/zXJbkH9FyoMQzVgQ0ysiDoP1KHd6a+HWbv5NcMSPGTgMNu48AAA=="
  },
  "dolphins-muscat": {
    "src": "/images/dolphins-muscat.webp",
    "width": 2400,
    "height": 1598,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JZQC7AB9eeczJhqNIe7WAANvtExiEn1Fd/UmYRIJB0AfhNOLawG86Syottz8VQdZmhem2IBx8vYxsw+Y3V+xrmJFAbPlmT2KAKwqFHRI42MLNHYhIISJss5FgAA=="
  },
  "dhow-turquoise": {
    "src": "/images/dhow-turquoise.webp",
    "width": 2400,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBQCdASoYABIAPu1sq1EppaOiqAqpMB2JZACdMuN1XvgALNyXgf6wpLN4BQRX1bDB7t4AAP7ftbbd9M2lefdmaQFAEIFq3ByzCryeojrIaQPHwcmkI7SbEmnwLBvLO8QkFUYYYNDXlqhoS00Tiz7SHKqx4JURYtyrRR5c/vyKXkppUFpfM52Gfy6GsD418ubIjj4LAAA="
  },
  "bimmah-sinkhole": {
    "src": "/images/bimmah-sinkhole.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZQDG9CG5aGjDm5eFKnAAyQF3AEy4ERik08s/c0tET8GiJXNkrlJlwwDG70IzWtV5151dYHcYXPa1PkyRJmBJqw16NH5kqO+jnvPGGB0zVPJLX70Xki0RiNHhRvSNHS+zyI1oY4RwjjIaZ6V3O8BURQZXcQRjcvM31BIeijgAAA=="
  },
  "grand-mosque-chandelier": {
    "src": "/images/grand-mosque-chandelier.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoMxmo3AXxLgBn35rstsXDPbeAAA/qaeLPOEwFvBaY0t+PneSnAKmBKKf4ejb39gWnkJ8geFHVPhzlmKfquvky9YTgiiCXJX1a4F1MFXcFdYjmYSO8ythkTRaR3guME1nHhDm+1Qw5Qr43t5p5rPs9/4rB+z/iwkY89k/m/3BYvt0OIAAAA="
  },
  "sur-lighthouse": {
    "src": "/images/sur-lighthouse.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAwCdASoYABAAPu1kqU2ppaQiMAgBMB2JQBOgBDv1d+cepLrYAP5QUN6UoNS3uIw50qYL4wCZDEOfIKSAIGG0BsL6WQTQHNCol4AL0E+2DJ+zIv+9gDfnjgQBpsuCtpoAAA=="
  },
  "extra-al-alam-palace": {
    "src": "/images/extra-al-alam-palace.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JbACdMoRwIsAAszakbjLuVYRw+gAAyoxzgnPoaQW093i82QL5+68b2YwAQGKCWv1bWhvOsapY0Ng1/g2/AgUVVuk6draevAZTKSWI55mm0KsAdtzxrhMoTaMdqYxi9zzn2lzXjBATXLVSEF71fIry6zqHIgfH4d0AAA=="
  }
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof images;
