// Generated by scripts/optimize-videos.mjs. Do not edit by hand.
export type VideoAsset = {
  key: string;
  mp4: string;
  webm: string | null;
  poster: string;
  blurDataURL: string;
  width: number;
  height: number;
  duration: number;
  bytes: number;
  position: string;
};

export const videos: Record<string, VideoAsset> = {
  "hero-oman-drone": {"key":"hero-oman-drone","mp4":"/videos/hero-oman-drone.mp4","webm":"/videos/hero-oman-drone.webm","poster":"/videos/hero-oman-drone-poster.webp","blurDataURL":"data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoYAA4APu1oqk6ppiQiMAgBMB2JQBOmUABsKZrEdXfI5EAA/eOcolYJ+3eamcComP5CT2HD8C7c4lRa89cUT82fksd+C6jDfl+xq2waVRJzNannpVHRhfdQJueiywIbk/y9V3XQ1IaEgYdfgJ9wAA==","width":1280,"height":720,"duration":5,"bytes":1713359,"position":"50% 60%"},
  "clip-muscat": {"key":"clip-muscat","mp4":"/videos/clip-muscat.mp4","webm":"/videos/clip-muscat.webm","poster":"/videos/clip-muscat-poster.webp","blurDataURL":"data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYAA4APu1kqU4ppaOiMAgBMB2JZQDE2CHfJPXD1VEUIAAA/vRQEuggQKmsOplPKVFuc8mijuy9Pnx+kUCZyxXsL5EBErPytT4p9QAA","width":960,"height":540,"duration":7.1,"bytes":264384,"position":"50% 50%"},
  "clip-wadi-shab": {"key":"clip-wadi-shab","mp4":"/videos/clip-wadi-shab.mp4","webm":"/videos/clip-wadi-shab.webm","poster":"/videos/clip-wadi-shab-poster.webp","blurDataURL":"data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUAA0RmczIHJLL3YvnHzgAP38X8T1tCnjWK4rsLGvTR3fdWDWFLv7t0HvEzQhD8hH8XoWNmx9q2BEoAcAJbCWc5Xi9K6+ERWGmJLQZTPQzcJw+gSE9nbOuJ6FeE+ZwGgPS1OtjPz2AbB1c7VQvLDPjAAA","width":960,"height":540,"duration":7.4,"bytes":633008,"position":"50% 55%"},
};

export function getVideo(key: string | null | undefined): VideoAsset | null {
  return key ? (videos[key] ?? null) : null;
}
