// Generated by scripts/optimize-videos.mjs. Do not edit by hand.
export type VideoAsset = {
  key: string;
  mp4: string;
  webm: string | null;
  poster: string;
  blurDataURL: string;
  width: number;
  height: number;
  duration: number;
  bytes: number;
  position: string;
};

export const videos: Record<string, VideoAsset> = {
  "hero-oman-drone": {"key":"hero-oman-drone","mp4":"/videos/hero-oman-drone.mp4","webm":"/videos/hero-oman-drone.webm","poster":"/videos/hero-oman-drone-poster.webp","blurDataURL":"data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAwCdASoYAA4APu1krU2ppaSiMAgBMB2JZQABHbCC7H6hEWFqonSAAP79nBC7rhc9zRaZOCr4ZaaAdV53Lir13tCTcFvrQ8/bu++xt0b+ASz5Ki5WfSs+eeOTbeuBA9PlwAAA","width":1920,"height":1080,"duration":12,"bytes":10257167,"position":"50% 50%"},
  "clip-muscat": {"key":"clip-muscat","mp4":"/videos/clip-muscat.mp4","webm":null,"poster":"/videos/clip-muscat-poster.webp","blurDataURL":"data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYAA4APu1iqk2ppaQiMAgBMB2JZQDA3CHfJPV+JodyTIAA/vRQEuggQKmsOpkKMiydXbqmMLk4yyU7G+lm/pXvYR3qhFskhp3Yj4IAAAA=","width":960,"height":540,"duration":7.1,"bytes":268042,"position":"50% 50%"},
  "clip-wadi-shab": {"key":"clip-wadi-shab","mp4":"/videos/clip-wadi-shab.mp4","webm":null,"poster":"/videos/clip-wadi-shab-poster.webp","blurDataURL":"data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUABYYa09UeYpgcXaUn0AAP38X8T1tCnjWK4rClAi3AWE8QwGc7PtDjVeJ7r2qAKuvV7D8uV/ulhKwm9ODGvhWPDanUe7cREsC60VVVRN8uXXcj5LnL+qYvJHmGe8Xuae77MrJ0mMsS7wM5JwggAAAA==","width":960,"height":540,"duration":7.4,"bytes":653386,"position":"50% 55%"},
};

export function getVideo(key: string | null | undefined): VideoAsset | null {
  return key ? (videos[key] ?? null) : null;
}
